audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Greg and Polina Vanyntrub
  title:
  license_number:
  about_markdown: |
    There are many qualities and skills that go into being an excellent real estate professional - integrity, in-depth community and market knowledge, marketing savvy, effective negotiation skills and a high-quality professional network, all of which are hallmarks of how we work.

    That said, in our experience as real estate professionals, we also found that providing the very best service is essentially about putting our clients first. This means keeping ourselves accessible, being a good listeners as well as a good communicators, and responding quickly to your needs.

    This "client first" philosophy has always been our approach and it requires us to continually improve our skills and ways of doing business. In addition, we’ve found that the latest technologies are enabling us to do everything we’ve always done, only much more quickly and efficiently. They've also helped us to extend the range of services we provide to our clients.

    So when you decide that you'd like to buy or sell a home in the Minneapolis/Saint Paul Market area, please contact Greg or Polina
  brand: Vayntrub Group
  brokerage: RE/MAX
  market: Twin Cities
  address:
  phone: 612 250-5115
  phone_type:
  phone2:
  phone2_type:
  email: Vayntrub@results.net
  url: https://gregvayntrub.results.net

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://gregvayntrub.results.net/home-evaluation/
  second_CTA_text: Home Search
  second_CTA_URL: https://gregvayntrub.results.net/real-estate/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://gregvayntrub.results.net/home-evaluation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://gregvayntrub.results.net/real-estate/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://business.facebook.com/vayntrubgroup/?business_id=10153283000255325
  linkedin_url:
  youtube_url: https://www.youtube.com/channel/UCPf5tqlT37AMzKhaHWg_6yw?view_as=subscriber
  twitter_url: https://twitter.com/VayntrubGroup
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#DD1C2F'
  theme_color: '#191919'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
